# Generated by Django 4.2.6 on 2024-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nfcnum',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
