# Generated by Django 4.2.6 on 2024-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='date',
            field=models.DateField(),
        ),
    ]
